controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#Start added by me developer
api_login_check:
    path: /api/login_check

#End added by me developer